# Generated by Django 4.1.4 on 2023-01-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog_app', '0002_alter_comment_user_alter_entry_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='entry',
        ),
        migrations.AddField(
            model_name='comment',
            name='entry',
            field=models.ManyToManyField(related_name='comments', to='myblog_app.entry'),
        ),
    ]
