# Generated by Django 4.1.4 on 2023-01-13 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog_app', '0003_remove_entry_comments_remove_comment_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='comments',
            field=models.ManyToManyField(related_name='comments', to='myblog_app.comment'),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='entry',
        ),
        migrations.AddField(
            model_name='comment',
            name='entry',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myblog_app.entry'),
            preserve_default=False,
        ),
    ]
